// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskYojitsu.Infrastructure.Persistence;

#nullable disable

namespace TaskYojitsu.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tyj")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "tyj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "tyj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "tyj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CredentialId")
                        .HasName("pk_user_passkeys");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_passkeys_user_id");

                    b.ToTable("user_passkeys", "tyj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorHint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_hint");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("PrevHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("prev_hash");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("result");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_action_occurred_at");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_actor_id_occurred_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_logs_target_type_target_id");

                    b.ToTable("audit_logs", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_result", "result IN ('success', 'failure', 'denied')");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("TaskId", "CreatedAt")
                        .HasDatabaseName("ix_comments_task_id_created_at");

                    b.HasIndex("TeamId", "TaskId")
                        .HasDatabaseName("ix_comments_team_id_task_id");

                    b.ToTable("comments", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_comments_body", "char_length(body) >= 1");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Holiday", b =>
                {
                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holiday_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("HolidayDate")
                        .HasName("pk_holidays");

                    b.ToTable("holidays", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_invitations_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_invitations_user_id");

                    b.ToTable("invitations", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_notifications_task_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_notifications_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_unread")
                        .HasFilter("read_at IS NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_notifications_kind", "kind IN ('task_assigned', 'task_unassigned', 'comment_added', 'due_tomorrow', 'overdue', 'team_added')");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("RequestIp")
                        .HasColumnType("inet")
                        .HasColumnName("request_ip");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_saved_views");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_saved_views_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_saved_views_team_id");

                    b.ToTable("saved_views", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_saved_views_conditions", "octet_length(conditions::text) <= 4096");

                            t.HasCheckConstraint("ck_saved_views_shared", "NOT is_shared OR team_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasAlternateKey("TeamId", "Id")
                        .HasName("ak_tags_team_id_id");

                    b.ToTable("tags", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_tags_color", "color IN ('gray', 'blue', 'green', 'yellow', 'orange', 'red', 'purple', 'teal')");

                            t.HasCheckConstraint("ck_tags_name", "char_length(name) >= 1");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("PredecessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_id");

                    b.Property<Guid>("SuccessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("successor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("PredecessorId", "SuccessorId")
                        .HasName("pk_task_dependencies");

                    b.HasIndex("SuccessorId")
                        .HasDatabaseName("ix_task_dependencies_successor_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_task_dependencies_team_id");

                    b.HasIndex("TeamId", "PredecessorId")
                        .HasDatabaseName("ix_task_dependencies_team_id_predecessor_id");

                    b.HasIndex("TeamId", "SuccessorId")
                        .HasDatabaseName("ix_task_dependencies_team_id_successor_id");

                    b.ToTable("task_dependencies", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_task_dependencies_self", "predecessor_id <> successor_id");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Field")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("new_value");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_task_histories");

                    b.HasIndex("TaskId", "OccurredAt")
                        .HasDatabaseName("ix_task_histories_task_id_occurred_at");

                    b.HasIndex("TeamId", "TaskId")
                        .HasDatabaseName("ix_task_histories_team_id_task_id");

                    b.ToTable("task_histories", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualEnd")
                        .HasColumnType("date")
                        .HasColumnName("actual_end");

                    b.Property<DateOnly?>("ActualStart")
                        .HasColumnType("date")
                        .HasColumnName("actual_start");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DeleteBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("delete_batch_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<short>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("depth");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_milestone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date")
                        .HasColumnName("planned_end");

                    b.Property<int?>("PlannedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("planned_minutes");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("priority");

                    b.Property<short>("Progress")
                        .HasColumnType("smallint")
                        .HasColumnName("progress");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("result_note");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasAlternateKey("TeamId", "Id")
                        .HasName("ak_tasks_team_id_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tasks_assignee_id")
                        .HasFilter("deleted_at IS NULL AND status NOT IN ('done', 'cancelled')");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_tasks_created_by");

                    b.HasIndex("DeleteBatchId")
                        .HasDatabaseName("ix_tasks_delete_batch_id")
                        .HasFilter("delete_batch_id IS NOT NULL");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_tasks_parent_id");

                    b.HasIndex("TeamId", "AssigneeId")
                        .HasDatabaseName("ix_tasks_team_id_assignee_id");

                    b.HasIndex("TeamId", "ParentId", "SortOrder")
                        .HasDatabaseName("ix_tasks_team_id_parent_id_sort_order")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TeamId", "PlannedStart", "PlannedEnd")
                        .HasDatabaseName("ix_tasks_team_id_planned_start_planned_end")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tasks", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_tasks_actual_order", "actual_end >= actual_start");

                            t.HasCheckConstraint("ck_tasks_depth", "depth BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tasks_done", "status <> 'done' OR (actual_end IS NOT NULL AND progress = 100)");

                            t.HasCheckConstraint("ck_tasks_milestone", "NOT is_milestone OR (planned_start = planned_end AND COALESCE(planned_minutes, 0) = 0)");

                            t.HasCheckConstraint("ck_tasks_planned_minutes", "planned_minutes BETWEEN 0 AND 599940 AND planned_minutes % 15 = 0");

                            t.HasCheckConstraint("ck_tasks_planned_order", "planned_end >= planned_start");

                            t.HasCheckConstraint("ck_tasks_planned_pair", "(planned_start IS NULL) = (planned_end IS NULL)");

                            t.HasCheckConstraint("ck_tasks_priority", "priority IN ('high', 'medium', 'low')");

                            t.HasCheckConstraint("ck_tasks_progress", "progress BETWEEN 0 AND 100 AND progress % 5 = 0");

                            t.HasCheckConstraint("ck_tasks_status", "status IN ('not_started', 'in_progress', 'on_hold', 'done', 'cancelled')");

                            t.HasCheckConstraint("ck_tasks_title", "char_length(title) >= 1");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskTag", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("TaskId", "TagId")
                        .HasName("pk_task_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_task_tags_tag_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_task_tags_team_id");

                    b.HasIndex("TeamId", "TagId")
                        .HasDatabaseName("ix_task_tags_team_id_tag_id");

                    b.HasIndex("TeamId", "TaskId")
                        .HasDatabaseName("ix_task_tags_team_id_task_id");

                    b.ToTable("task_tags", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("archived_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.ToTable("teams", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_teams_name", "char_length(name) >= 1");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid?>("RemovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("removed_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id")
                        .HasFilter("removed_at IS NULL");

                    b.ToTable("team_members", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_team_members_role", "role IN ('leader', 'member')");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DefaultViewId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_view_id");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<long?>("LastTotpStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_step");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DefaultViewId")
                        .HasDatabaseName("ix_users_default_view_id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_users_active_has_password", "status <> 'active' OR password_hash IS NOT NULL");

                            t.HasCheckConstraint("ck_users_status", "status IN ('invited', 'active', 'disabled')");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.UserKnownDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("fingerprint");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "Fingerprint")
                        .HasName("pk_user_known_devices");

                    b.ToTable("user_known_devices", "tyj");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("auth_method");

                    b.Property<DateTime>("AuthTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auth_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("Ip")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revoked_reason");

                    b.Property<byte[]>("Ticket")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ticket");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_key_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_user_sessions_user_id_revoked_at");

                    b.ToTable("user_sessions", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_user_sessions_auth_method", "auth_method IN ('password', 'password_totp', 'password_recovery', 'passkey')");

                            t.HasCheckConstraint("ck_user_sessions_revoked_reason", "revoked_reason IS NULL OR revoked_reason IN ('logout', 'password_changed', 'mfa_changed', 'disabled', 'user_revoked', 'admin_revoked')");
                        });
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.WorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("source");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id")
                        .HasName("pk_work_logs");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_work_logs_task_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_work_logs_team_id");

                    b.HasIndex("TeamId", "TaskId")
                        .HasDatabaseName("ix_work_logs_team_id_task_id");

                    b.HasIndex("UserId", "WorkDate")
                        .HasDatabaseName("ix_work_logs_user_id_work_date");

                    b.ToTable("work_logs", "tyj", t =>
                        {
                            t.HasCheckConstraint("ck_work_logs_minutes", "minutes BETWEEN 15 AND 1440 AND minutes % 15 = 0");

                            t.HasCheckConstraint("ck_work_logs_source", "source IN ('dialog', 'timesheet')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<System.Guid>", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_passkeys_users_user_id");

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("user_passkeys", "tyj");

                            b1
                                .ToJson("data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Comment", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "TaskId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_tasks_team_id_task_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_tasks_task_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_teams_team_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.SavedView", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_views_users_owner_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_saved_views_teams_team_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.Tag", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tags_teams_team_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskDependency", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "PredecessorId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_tasks_team_id_predecessor_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "SuccessorId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_dependencies_tasks_team_id_successor_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "TaskId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_histories_tasks_team_id_task_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_users_created_by");

                    b.HasOne("TaskYojitsu.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_teams_team_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_team_members_team_id_assignee_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "ParentId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tasks_tasks_team_id_parent_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TaskTag", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "TagId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tags_team_id_tag_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "TaskId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_tags_tasks_team_id_task_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.User", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.SavedView", null)
                        .WithMany()
                        .HasForeignKey("DefaultViewId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_saved_views_default_view_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.UserKnownDevice", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_known_devices_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });

            modelBuilder.Entity("TaskYojitsu.Domain.Entities.WorkLog", b =>
                {
                    b.HasOne("TaskYojitsu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_users_user_id");

                    b.HasOne("TaskYojitsu.Domain.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TeamId", "TaskId")
                        .HasPrincipalKey("TeamId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_logs_tasks_team_id_task_id");
                });
#pragma warning restore 612, 618
        }
    }
}
