<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TaskYojitsu.Tool</RootNamespace>
    <AssemblyName>taskyojitsu-tool</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskYojitsu.Application\TaskYojitsu.Application.csproj" />
    <ProjectReference Include="..\TaskYojitsu.Infrastructure\TaskYojitsu.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
